import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "@/styles/reset.css";
import "@/styles/globals.css";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const poppinsFont = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Trendway",
  description: "Generated by Kağan Çubukçu",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppinsFont.className}>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
